// Code generated by protoc-gen-go.
// source: core.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// TestToAgent TestToAgent
type TestToAgent struct {
	FieldA string `protobuf:"bytes,1,opt,name=FieldA" json:"FieldA,omitempty"`
}

func (m *TestToAgent) Reset()                    { *m = TestToAgent{} }
func (m *TestToAgent) String() string            { return proto.CompactTextString(m) }
func (*TestToAgent) ProtoMessage()               {}
func (*TestToAgent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// TestToGame TestToGame
type TestToGame struct {
	FieldA string `protobuf:"bytes,1,opt,name=FieldA" json:"FieldA,omitempty"`
	FieldB string `protobuf:"bytes,2,opt,name=FieldB" json:"FieldB,omitempty"`
}

func (m *TestToGame) Reset()                    { *m = TestToGame{} }
func (m *TestToGame) String() string            { return proto.CompactTextString(m) }
func (*TestToGame) ProtoMessage()               {}
func (*TestToGame) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// UpPing UpPing
type UpPing struct {
}

func (m *UpPing) Reset()                    { *m = UpPing{} }
func (m *UpPing) String() string            { return proto.CompactTextString(m) }
func (*UpPing) ProtoMessage()               {}
func (*UpPing) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// DownPing DownPing
type DownPing struct {
}

func (m *DownPing) Reset()                    { *m = DownPing{} }
func (m *DownPing) String() string            { return proto.CompactTextString(m) }
func (*DownPing) ProtoMessage()               {}
func (*DownPing) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// web请求
// register?data={{json}}&syn={{syn}}
// WebUpRegister 上发游客登录，使用http上发游客登录
type WebUpRegister struct {
	MachineCode string `protobuf:"bytes,1,opt,name=MachineCode" json:"MachineCode,omitempty"`
}

func (m *WebUpRegister) Reset()                    { *m = WebUpRegister{} }
func (m *WebUpRegister) String() string            { return proto.CompactTextString(m) }
func (*WebUpRegister) ProtoMessage()               {}
func (*WebUpRegister) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// WebDownRegister 下发游客登录
type WebDownRegister struct {
	UserID      string      `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Password    string      `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Info        *ServerInfo `protobuf:"bytes,3,opt,name=Info" json:"Info,omitempty"`
	Cookie      string      `protobuf:"bytes,4,opt,name=Cookie" json:"Cookie,omitempty"`
	MachineCode string      `protobuf:"bytes,5,opt,name=MachineCode" json:"MachineCode,omitempty"`
}

func (m *WebDownRegister) Reset()                    { *m = WebDownRegister{} }
func (m *WebDownRegister) String() string            { return proto.CompactTextString(m) }
func (*WebDownRegister) ProtoMessage()               {}
func (*WebDownRegister) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *WebDownRegister) GetInfo() *ServerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// web请求
// login?data={{json}}&syn={{syn}}
// WebUpGetServerInfo 使用http登录
type WebUpGetServerInfo struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *WebUpGetServerInfo) Reset()                    { *m = WebUpGetServerInfo{} }
func (m *WebUpGetServerInfo) String() string            { return proto.CompactTextString(m) }
func (*WebUpGetServerInfo) ProtoMessage()               {}
func (*WebUpGetServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

// WebDownGetServerInfo 下发http登录
type WebDownGetServerInfo struct {
	Info   *ServerInfo `protobuf:"bytes,1,opt,name=Info" json:"Info,omitempty"`
	UserID string      `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
	Cookie string      `protobuf:"bytes,3,opt,name=Cookie" json:"Cookie,omitempty"`
}

func (m *WebDownGetServerInfo) Reset()                    { *m = WebDownGetServerInfo{} }
func (m *WebDownGetServerInfo) String() string            { return proto.CompactTextString(m) }
func (*WebDownGetServerInfo) ProtoMessage()               {}
func (*WebDownGetServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *WebDownGetServerInfo) GetInfo() *ServerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// ServerInfo ServerInfo
type ServerInfo struct {
	AgentIP   string `protobuf:"bytes,1,opt,name=AgentIP" json:"AgentIP,omitempty"`
	AgentPort string `protobuf:"bytes,2,opt,name=AgentPort" json:"AgentPort,omitempty"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

// UpGetConfigToCenter 向中心服请求配置表
type UpGetConfigToCenter struct {
}

func (m *UpGetConfigToCenter) Reset()                    { *m = UpGetConfigToCenter{} }
func (m *UpGetConfigToCenter) String() string            { return proto.CompactTextString(m) }
func (*UpGetConfigToCenter) ProtoMessage()               {}
func (*UpGetConfigToCenter) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

// SyncConfigData 同步数据
type SyncConfigDataToAll struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *SyncConfigDataToAll) Reset()                    { *m = SyncConfigDataToAll{} }
func (m *SyncConfigDataToAll) String() string            { return proto.CompactTextString(m) }
func (*SyncConfigDataToAll) ProtoMessage()               {}
func (*SyncConfigDataToAll) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

// LoginKickPlayerToAgent 登录服踢出玩家
type LoginKickPlayerToAgent struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *LoginKickPlayerToAgent) Reset()                    { *m = LoginKickPlayerToAgent{} }
func (m *LoginKickPlayerToAgent) String() string            { return proto.CompactTextString(m) }
func (*LoginKickPlayerToAgent) ProtoMessage()               {}
func (*LoginKickPlayerToAgent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

// PlayerLoginToUnique  向登陆服请求玩家数据
type PlayerLoginToUnique struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Cookie string `protobuf:"bytes,2,opt,name=Cookie" json:"Cookie,omitempty"`
}

func (m *PlayerLoginToUnique) Reset()                    { *m = PlayerLoginToUnique{} }
func (m *PlayerLoginToUnique) String() string            { return proto.CompactTextString(m) }
func (*PlayerLoginToUnique) ProtoMessage()               {}
func (*PlayerLoginToUnique) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

// LoginCheckPlayerToAgent 检查登录的玩家是否合法
type LoginCheckPlayerToAgent struct {
	UserID  string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	IsLegal bool   `protobuf:"varint,2,opt,name=IsLegal" json:"IsLegal,omitempty"`
}

func (m *LoginCheckPlayerToAgent) Reset()                    { *m = LoginCheckPlayerToAgent{} }
func (m *LoginCheckPlayerToAgent) String() string            { return proto.CompactTextString(m) }
func (*LoginCheckPlayerToAgent) ProtoMessage()               {}
func (*LoginCheckPlayerToAgent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

// PlayerLoginToGame 玩家向游戏服请求数据
type PlayerLoginToGame struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *PlayerLoginToGame) Reset()                    { *m = PlayerLoginToGame{} }
func (m *PlayerLoginToGame) String() string            { return proto.CompactTextString(m) }
func (*PlayerLoginToGame) ProtoMessage()               {}
func (*PlayerLoginToGame) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

// DownPlayerLogin 玩家登陆成功
type DownPlayerLogin struct {
	RoleID    int32  `protobuf:"varint,1,opt,name=RoleID" json:"RoleID,omitempty"`
	IsSucceed bool   `protobuf:"varint,2,opt,name=IsSucceed" json:"IsSucceed,omitempty"`
	UserID    string `protobuf:"bytes,3,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *DownPlayerLogin) Reset()                    { *m = DownPlayerLogin{} }
func (m *DownPlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*DownPlayerLogin) ProtoMessage()               {}
func (*DownPlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

// WebUpRegisterPassword?data={{json}}&syn={{syn}}
// WebUpRegisterPassword 上发注册，使用http上发注册 加上密码
type WebUpRegisterPassword struct {
	UserID   string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=Code" json:"Code,omitempty"`
}

func (m *WebUpRegisterPassword) Reset()                    { *m = WebUpRegisterPassword{} }
func (m *WebUpRegisterPassword) String() string            { return proto.CompactTextString(m) }
func (*WebUpRegisterPassword) ProtoMessage()               {}
func (*WebUpRegisterPassword) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

// WebDownRegisterPassword 下发注册
type WebDownRegisterPassword struct {
	UserID string      `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Info   *ServerInfo `protobuf:"bytes,2,opt,name=Info" json:"Info,omitempty"`
	Cookie string      `protobuf:"bytes,3,opt,name=Cookie" json:"Cookie,omitempty"`
}

func (m *WebDownRegisterPassword) Reset()                    { *m = WebDownRegisterPassword{} }
func (m *WebDownRegisterPassword) String() string            { return proto.CompactTextString(m) }
func (*WebDownRegisterPassword) ProtoMessage()               {}
func (*WebDownRegisterPassword) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *WebDownRegisterPassword) GetInfo() *ServerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// TestStruct mergepb工具
type TestStruct struct {
	FieldA string `protobuf:"bytes,1,opt,name=FieldA" json:"FieldA,omitempty"`
	FieldB bool   `protobuf:"varint,2,opt,name=FieldB" json:"FieldB,omitempty"`
}

func (m *TestStruct) Reset()                    { *m = TestStruct{} }
func (m *TestStruct) String() string            { return proto.CompactTextString(m) }
func (*TestStruct) ProtoMessage()               {}
func (*TestStruct) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func init() {
	proto.RegisterType((*TestToAgent)(nil), "pb.TestToAgent")
	proto.RegisterType((*TestToGame)(nil), "pb.TestToGame")
	proto.RegisterType((*UpPing)(nil), "pb.UpPing")
	proto.RegisterType((*DownPing)(nil), "pb.DownPing")
	proto.RegisterType((*WebUpRegister)(nil), "pb.WebUpRegister")
	proto.RegisterType((*WebDownRegister)(nil), "pb.WebDownRegister")
	proto.RegisterType((*WebUpGetServerInfo)(nil), "pb.WebUpGetServerInfo")
	proto.RegisterType((*WebDownGetServerInfo)(nil), "pb.WebDownGetServerInfo")
	proto.RegisterType((*ServerInfo)(nil), "pb.ServerInfo")
	proto.RegisterType((*UpGetConfigToCenter)(nil), "pb.UpGetConfigToCenter")
	proto.RegisterType((*SyncConfigDataToAll)(nil), "pb.SyncConfigDataToAll")
	proto.RegisterType((*LoginKickPlayerToAgent)(nil), "pb.LoginKickPlayerToAgent")
	proto.RegisterType((*PlayerLoginToUnique)(nil), "pb.PlayerLoginToUnique")
	proto.RegisterType((*LoginCheckPlayerToAgent)(nil), "pb.LoginCheckPlayerToAgent")
	proto.RegisterType((*PlayerLoginToGame)(nil), "pb.PlayerLoginToGame")
	proto.RegisterType((*DownPlayerLogin)(nil), "pb.DownPlayerLogin")
	proto.RegisterType((*WebUpRegisterPassword)(nil), "pb.WebUpRegisterPassword")
	proto.RegisterType((*WebDownRegisterPassword)(nil), "pb.WebDownRegisterPassword")
	proto.RegisterType((*TestStruct)(nil), "pb.TestStruct")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0x9c, 0x34, 0xb8, 0x13, 0x41, 0x85, 0x43, 0x5b, 0x0b, 0x71, 0xa8, 0x56, 0x42, 0x02,
	0x21, 0x45, 0x7c, 0x5c, 0xb9, 0xb4, 0x0e, 0x54, 0x56, 0x03, 0xb2, 0x9c, 0x44, 0x1c, 0x91, 0x63,
	0x4f, 0x5d, 0x53, 0x77, 0xd7, 0xac, 0x37, 0x54, 0xfd, 0x3d, 0xfc, 0x51, 0xd6, 0xeb, 0xf5, 0x57,
	0x68, 0x43, 0xc4, 0x6d, 0xdf, 0x78, 0xe7, 0xbd, 0x37, 0xe3, 0x99, 0x05, 0x08, 0x19, 0xc7, 0x49,
	0xc6, 0x99, 0x60, 0x96, 0x91, 0xad, 0xc8, 0x4b, 0x18, 0x2d, 0x30, 0x17, 0x0b, 0x76, 0x1a, 0x23,
	0x15, 0xd6, 0x11, 0x0c, 0x3f, 0x27, 0x98, 0x46, 0xa7, 0x76, 0xef, 0xa4, 0xf7, 0x6a, 0xdf, 0xd7,
	0x88, 0x7c, 0x04, 0x28, 0xaf, 0x9d, 0x07, 0x37, 0xf8, 0xd0, 0xad, 0x3a, 0x7e, 0x66, 0x1b, 0xad,
	0xf8, 0x19, 0x31, 0x61, 0xb8, 0xcc, 0xbc, 0x84, 0xc6, 0x04, 0xc0, 0x9c, 0xb2, 0x5b, 0xaa, 0xce,
	0xef, 0xe0, 0xf1, 0x37, 0x5c, 0x2d, 0x33, 0x1f, 0xe3, 0x24, 0x17, 0xc8, 0xad, 0x13, 0x18, 0x7d,
	0x09, 0xc2, 0xab, 0x84, 0xa2, 0xc3, 0x22, 0xd4, 0xdc, 0xed, 0x10, 0xf9, 0xdd, 0x83, 0x03, 0x99,
	0x53, 0x50, 0xd4, 0x59, 0x52, 0x74, 0x99, 0x23, 0x77, 0xa7, 0x95, 0x99, 0x12, 0x59, 0xcf, 0xc1,
	0xf4, 0x82, 0x3c, 0xbf, 0x65, 0x3c, 0xd2, 0x76, 0x6a, 0x6c, 0x11, 0x18, 0xb8, 0xf4, 0x92, 0xd9,
	0x7d, 0x19, 0x1f, 0xbd, 0x7f, 0x32, 0xc9, 0x56, 0x93, 0x39, 0xf2, 0x5f, 0x32, 0x4f, 0x46, 0x7d,
	0xf5, 0xad, 0xe0, 0x75, 0x18, 0xbb, 0x4e, 0xd0, 0x1e, 0x94, 0xbc, 0x25, 0xda, 0x74, 0xb9, 0xf7,
	0xb7, 0xcb, 0x19, 0x58, 0xaa, 0xb0, 0x73, 0x14, 0x0d, 0x6b, 0xe1, 0xa7, 0x70, 0xf6, 0x55, 0x36,
	0x50, 0x3b, 0xad, 0xf1, 0x36, 0xaf, 0xe4, 0x07, 0x3c, 0xd3, 0x25, 0x77, 0xf9, 0xaa, 0x1a, 0x7a,
	0xdb, 0x6b, 0xd0, 0xbd, 0x31, 0x3a, 0xbd, 0x69, 0x6a, 0xeb, 0xb7, 0x6b, 0x23, 0x53, 0x80, 0x96,
	0x82, 0x0d, 0x8f, 0xd4, 0x54, 0xb8, 0x9e, 0x36, 0x5c, 0x41, 0xeb, 0x05, 0xec, 0xab, 0xa3, 0xc7,
	0xb8, 0xd0, 0xd4, 0x4d, 0x80, 0x1c, 0xc2, 0x58, 0x15, 0xef, 0x30, 0x7a, 0x99, 0xc4, 0x0b, 0xe6,
	0xc8, 0x0f, 0xc8, 0xc9, 0x6b, 0x18, 0xcf, 0xef, 0x68, 0x58, 0x46, 0xa7, 0x81, 0x08, 0xe4, 0xd0,
	0xa5, 0xa9, 0x65, 0xc1, 0x20, 0x92, 0x40, 0x4b, 0xa8, 0x33, 0x79, 0x0b, 0x47, 0x33, 0x16, 0x27,
	0xf4, 0x22, 0x09, 0xaf, 0xbd, 0x34, 0xb8, 0x43, 0xde, 0x1a, 0xd0, 0xfb, 0xfe, 0x36, 0xf9, 0x04,
	0xe3, 0xf2, 0xa2, 0xca, 0x5b, 0xb0, 0x25, 0x4d, 0x7e, 0xae, 0xf1, 0xc1, 0xe1, 0x68, 0x1a, 0x60,
	0x74, 0x1a, 0x70, 0x01, 0xc7, 0x8a, 0xc0, 0xb9, 0xc2, 0x1d, 0x95, 0x8b, 0x2e, 0xb9, 0xf9, 0x0c,
	0xe3, 0x20, 0x55, 0x5c, 0xa6, 0x5f, 0x41, 0xf2, 0x06, 0x9e, 0x76, 0x3c, 0x55, 0xbb, 0x73, 0x6f,
	0x01, 0xdf, 0xe1, 0x40, 0x6d, 0x46, 0x93, 0x50, 0x5c, 0xf5, 0x59, 0x8a, 0xfa, 0xea, 0x9e, 0xaf,
	0x51, 0xd1, 0x7d, 0x37, 0x9f, 0xaf, 0xc3, 0x10, 0x31, 0xd2, 0x9a, 0x4d, 0xa0, 0x25, 0xd0, 0xdf,
	0x10, 0x38, 0xec, 0xac, 0x5b, 0xbd, 0x0c, 0xff, 0xb3, 0x40, 0xf2, 0xa7, 0xa9, 0xe9, 0x2f, 0x25,
	0xd4, 0x99, 0xdc, 0xc0, 0xf1, 0xc6, 0x6e, 0xfe, 0x53, 0xa2, 0x9a, 0x61, 0x63, 0xa7, 0x3d, 0xec,
	0xce, 0xaa, 0x7e, 0x92, 0xe6, 0x82, 0xaf, 0x43, 0xb1, 0xe3, 0x93, 0x64, 0x56, 0x4f, 0xd2, 0x6a,
	0xa8, 0x9e, 0xc0, 0x0f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x28, 0x81, 0x39, 0x29, 0x10, 0x05,
	0x00, 0x00,
}
