package pb

// Code generated by gen_proto.sh.
// DO NOT EDIT!

import (
	"github.com/chaos007/easycome/msgmeta"
)

func init() {
	msgmeta.RegisterMessageMeta("pb.BackendLogin", 1)
	msgmeta.RegisterMessageMeta("pb.UpGetBackendLoginInfo", 2)
	msgmeta.RegisterMessageMeta("pb.DownGetBackendLoginInfo", 3)
	msgmeta.RegisterMessageMeta("pb.UpPing", 4)
	msgmeta.RegisterMessageMeta("pb.DownPing", 5)
	msgmeta.RegisterMessageMeta("pb.WebUpRegister", 6)
	msgmeta.RegisterMessageMeta("pb.WebDownRegister", 7)
	msgmeta.RegisterMessageMeta("pb.WebUpGetServerInfo", 8)
	msgmeta.RegisterMessageMeta("pb.WebDownGetServerInfo", 9)
	msgmeta.RegisterMessageMeta("pb.ServerInfo", 10)
	msgmeta.RegisterMessageMeta("pb.UpGetConfigToCenter", 11)
	msgmeta.RegisterMessageMeta("pb.SyncConfigDataToAll", 12)
	msgmeta.RegisterMessageMeta("pb.LoginKickPlayerToAgent", 13)
	msgmeta.RegisterMessageMeta("pb.PlayerLoginToUnique", 14)
	msgmeta.RegisterMessageMeta("pb.LoginCheckPlayerToAgent", 15)
	msgmeta.RegisterMessageMeta("pb.PlayerLoginToGame", 16)
	msgmeta.RegisterMessageMeta("pb.DownPlayerLogin", 17)
	msgmeta.RegisterMessageMeta("pb.WebUpRegisterPassword", 18)
	msgmeta.RegisterMessageMeta("pb.WebDownRegisterPassword", 19)
	msgmeta.RegisterMessageMeta("pb.TestStruct", 20)
	msgmeta.RegisterMessageMeta("pb.TestToAgent", 21)
	msgmeta.RegisterMessageMeta("pb.TestToGame", 22)
	msgmeta.RegisterMessageMeta("pb.UpJoinRoomToUnique", 23)
	msgmeta.RegisterMessageMeta("pb.DownJoinRoomToClient", 24)
	msgmeta.RegisterMessageMeta("pb.NoticeJoinRoomToClient", 25)
	msgmeta.RegisterMessageMeta("pb.UpSendMessageToGame", 26)
	msgmeta.RegisterMessageMeta("pb.DownSendMessageToClient", 27)
	msgmeta.RegisterMessageMeta("pb.NoticeSendMessageToClient", 28)
	msgmeta.RegisterMessageMeta("pb.JoinRoomServerIDToAgent", 29)

}
